### ISSUE TITLE
Invalid Syntax: alg:str

### ISSUE THREAD

**Issue by johnli2210** [GehirnInc/python-jwt#24]
Trying to import `jwt==0.5.4` in Py2.7: 

```
Python 2.7.12 (default, Nov 12 2018, 14:36:49) 
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import jwt
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/johnli/.local/lib/python2.7/site-packages/jwt/__init__.py", line 17, in <module>
    from .jwa import std_hash_by_alg
  File "/home/johnli/.local/lib/python2.7/site-packages/jwt/jwa.py", line 31
    def std_hash_by_alg(alg: str) -> Callable[[bytes], object]:
                           ^
SyntaxError: invalid syntax
```

**Comment by yosida95** [comment]
As we describe in README, python-jwt does not support Python 2.X at all.
https://github.com/GehirnInc/python-jwt#supported-python-versions
