### ISSUE TITLE
Unable to import under Python 3.8

### ISSUE THREAD

**Issue by wlad** [GehirnInc/python-jwt#27]
```
(venv) wlad@hypervubu:~/projects/ehrbase/tests$ python
Python 3.8.2 (default, Apr 16 2020, 20:42:22) 
[GCC 9.2.1 20191008] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import json
>>> from datetime import datetime, timedelta, timezone
>>> from jwt import JWT
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'JWT' from 'jwt' (unknown location)
>>> from jwt import jwt
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/wlad/.local/lib/python3.8/site-packages/jwt/jwt.py", line 22, in <module>
    from jwt.utils import (
ModuleNotFoundError: No module named 'jwt.utils
```

**Comment by yosida95** [comment]
@wlad Please provide the output of `pip freeze`

**Comment by yosida95** [comment]
Close for now because of the inactivity and the tests are passing on Python 3.8+ https://travis-ci.org/github/GehirnInc/python-jwt/builds/740111308 . If you are still have this trouble, feel free to reopen this issue with the version of jwt and the method used to install jwt.
